# Usage:
#
# sudo docker-compose build
# sudo docker-compose up
#
# Remember to setup "./.env" to match your needs prior to build.
#
#
version: "2"
services:
    userver:
        env_file: .env
        image: "userver:v1"
        build:
            dockerfile: Dockerfile
            context: .
            args:
            - https_proxy=${https_proxy}
            - http_proxy=${http_proxy}
        ports:
        - "9035:9035" # Default http port
        volumes:
        - ${SSL_public_key}:/home/centos/.ssl/cert.pem
        - ${SSL_private_key}:/home/centos/.ssl/key.pem
        - ${DAT_DIR}:/usr/src/dat
        - ../volumes/logs:/usr/src/app/logs
        restart: "no"
